### ISSUE TITLE
online-функция

### ISSUE THREAD

**Issue by tardis-forever** [ashat1701/algo3sem#10]
https://github.com/ashat1701/algo3sem/blob/7ffee2defa25b15f016d16875a81e3bc91bbc9d3/first-contest/patternOccurance/patternOccurance.cpp#L21

С дизайном решения "считать обе строки, вывести ответ", функция с названием "online" смотрится очень странно.

**Comment by ashat1701** [comment]
https://contest.yandex.ru/contest/13875/run-report/21474198/
Переделал

**Comment by ashat1701** [comment]
Теперь передаю чисто поток
