### ISSUE TITLE
так как вся смысловая часть кода - копипаста другого файла - см. замечания к string-recover.cpp

### ISSUE THREAD

**Issue by tardis-forever** [ashat1701/algo3sem#20]
https://github.com/ashat1701/algo3sem/blob/7ffee2defa25b15f016d16875a81e3bc91bbc9d3/first-contest/string-recover/string-recover2.cpp#L7

**Comment by ashat1701** [comment]
https://contest.yandex.ru/contest/13875/run-report/21474339/
