### ISSUE TITLE
Для этого стоит написать конструктов TrieNode(int, int, int, int)

### ISSUE THREAD

**Issue by tardis-forever** [ashat1701/algo3sem#23]
https://github.com/ashat1701/algo3sem/blob/dbc85bde21f4c92bc116e8c2441758a782e94c6c/first-contest/lightRegex/light-regex.cpp#L62

https://github.com/ashat1701/algo3sem/blob/dbc85bde21f4c92bc116e8c2441758a782e94c6c/first-contest/lightRegex/light-regex.cpp#L75

**Comment by ashat1701** [comment]
https://contest.yandex.ru/contest/13875/run-report/21482435/
Переделал
