### ISSUE TITLE
TrieNode и trie должны быть private, потому что это внутренние вещи класса

### ISSUE THREAD

**Issue by tardis-forever** [ashat1701/algo3sem#25]
https://github.com/ashat1701/algo3sem/blob/dbc85bde21f4c92bc116e8c2441758a782e94c6c/first-contest/lightRegex/light-regex.cpp#L12

Доступ к ac.trie[cur_node].is_terminal нужно будет реализовать через отдельную функцию

**Comment by ashat1701** [comment]
Можно сделать grep friend

**Comment by ashat1701** [comment]
Хотя мб нет
