### ISSUE TITLE
Много лишних вызовов .length() от не изменяющихся строк, стоит вынести значения в переменную

### ISSUE THREAD

**Issue by tardis-forever** [ashat1701/algo3sem#26]
https://github.com/ashat1701/algo3sem/blob/7ffee2defa25b15f016d16875a81e3bc91bbc9d3/first-contest/patternOccurance/patternOccurance.cpp#L42

**Comment by ashat1701** [comment]
А почему кстати? Я смотрел профилировщиком callgrind и там было мало времени на вызов length. Мб прагма оптимайз? Так то вызов функции медленнее тут никто не спорит

**Comment by tardis-forever** [comment]
С большой вероятностью даже -O3 может многократные вызовы соптимизировать в локальную переменную, но это не значит, что не стоит этого сделать самому, чтобы код был более красивым и аккуратным

**Comment by ashat1701** [comment]
Я сделал

**Comment by ashat1701** [comment]
Но что по поводу префикс функции
