### ISSUE TITLE
Почему обработка первого символа отличается от всех остальных и вынесена за for?

### ISSUE THREAD

**Issue by tardis-forever** [ashat1701/algo3sem#4]
https://github.com/ashat1701/algo3sem/blob/7ffee2defa25b15f016d16875a81e3bc91bbc9d3/first-contest/patternOccurance/patternOccurance.cpp#L40

**Comment by ashat1701** [comment]
Потому что это создание ячейки где будет хранится текущая префикс функция.

**Comment by tardis-forever** [comment]
почему текущая префкис функция хранится в ячейке вектора, а не в переменной?

**Comment by ashat1701** [comment]
Кажется что это естественно. При этом не нужно модифицировать префикс функцию.

**Comment by tardis-forever** [comment]
хорошо
